### ISSUE TITLE
(UC 4) Aktivität teilen (Titel, Beschreibung)

### ISSUE THREAD

**Issue by CaBeckmann** [sweIhm/sweiproject-tg2b-6#1]
Als Student oder Mitarbeiter einer Hochschule/Universität möchte ich eine Aktivität mit einem Titel und einer Beschreibung teilen können.

**Akzeptanzkriterien**
- Teilen einer Aktivität als Student/Mitarbeiter einer Hochschule/Universität möglich
- Eingabe eines Titels möglich
- Eingabe einer Beschreibung möglich

**Comment by mariomeissner** [comment]
Diese Funktionalität wurde erfolgreich implementiert.
