### ISSUE TITLE
(UC 5) Aktivität kommentieren (Korrektur) 

### ISSUE THREAD

**Issue by Melanie217** [sweIhm/sweiproject-tg2b-6#10]
Als Student oder Mitarbeiter einer Hochschule/Universität möchte ich nach dem Kommentieren einer Aktivität eine Möglichkeit haben das Geschriebene zu ändern.

**Akzeptanzkriterien**

- Teilen eines Kommentars als Student/Mitarbeiter einer Hochschule/Universität möglich
- Möglichkeit zur Korrektur

**Comment by dariusl93** [comment]
Das Sprintziel wurde nicht erreicht. Nach dem zweiten Sprint ist das Löschen nur durch das Löschen der kompletten Activity möglich.

**Comment by mariomeissner** [comment]
Ich werde versuchen daran zu arbeiten.

**Comment by mariomeissner** [comment]
Works now.
