### ISSUE TITLE
(UC 1) Aktivitätenübersicht aufrufen

### ISSUE THREAD

**Issue by Melanie217** [sweIhm/sweiproject-tg2b-6#11]
Als Student oder Mitarbeiter einer Hochschule/Universität möchte ich beim eine Übersicht der Aktivitäten aufrufen können.

**Akzeptanzkriterien**

- Aufrufen der Übersicht der Aktivitäten möglich

**Comment by CaBeckmann** [comment]
Im ersten Sprint wird die Klasse Activity wie im folgenden Klassendiagramm (Documentation/Sprint1/Activities.png) erweitert:
![](https://github.com/sweIhm/sweiproject-tg2b-6/blob/master/Documentation/Sprint1/Activities.png)

In der Aktivitätenübersicht sollen von diesen Attributen Titel (title), Beschreibung (description) und Tags angezeigt werden.
