### ISSUE TITLE
(UC 1) Aktivitätenübersicht aufrufen (filtern) 

### ISSUE THREAD

**Issue by Melanie217** [sweIhm/sweiproject-tg2b-6#12]
Als Student oder Mitarbeiter einer Hochschule/Universität möchte ich beim Aufrufen der Aktivitätenübersicht die Möglichkeit haben, die Ergebnisse zu filtern.

**Akzeptanzkriterien**

- Aufrufen der Aktivitätenübersicht möglich
- Möglichkeit zur Filterung der Aktivitäten

**Comment by mariomeissner** [comment]
I will give support to filter the overview screen activities by tag, but for now only one. 
This may change in a future User Story.

**Comment by mariomeissner** [comment]
Implemented the changes.
