### ISSUE TITLE
(UC 6) Veranstalter kontaktieren

### ISSUE THREAD

**Issue by dariusl93** [sweIhm/sweiproject-tg2b-6#13]
Als Student oder Mitarbeiter einer Hochschule/Universität möchte ich bei bestehenden Interesse an einer Aktivität, den Veranstalter kontaktieren können.

Akzeptanzkriterien

- Nachdem eine Aktivität aufgerufen wurde, kann man den Veranstalter per E-Mail kontaktieren
- Durch den Aufruf eines Links, wird man auf sein E-Mailprogramm umgeleitet, in der die Empfängeradresse des Veranstalters angegeben ist.

**Comment by Melanie217** [comment]
Diese Funktion wurde implementiert.
