### ISSUE TITLE
(UC 3) Detailansicht einer Aktivität aufrufen

### ISSUE THREAD

**Issue by mariomeissner** [sweIhm/sweiproject-tg2b-6#19]
Als Student oder Mitarbeiter einer Hochschule/Universität möchte ich von der Übersicht aus eine Aktivität anklicken, um eine detaillierte Deskription der Aktivität zu lesen.

**Akzeptanzkriterien**
- Öffnen der Detailansicht der Aktivitäten möglich
- Deskription zur Aktivität lesbar.

**Comment by Melanie217** [comment]
Im ersten Sprint wird die Klasse Activity wie im folgenden Klassendiagramm (Documentation/Sprint1/Activities.png) erweitert: [https://github.com/sweIhm/sweiproject-tg2b-6/blob/master/Documentation/Sprint1/Activities.png](Link)

Die Aktivität soll beim aufrufen alle eingegebenen Informationen anzeigen.
