### ISSUE TITLE
(UC 4) Aktivität teilen (Kategorie)

### ISSUE THREAD

**Issue by CaBeckmann** [sweIhm/sweiproject-tg2b-6#2]
Als Student oder Mitarbeiter einer Hochschule/Universität möchte ich beim Teilen einer Aktivität eine Kategorie (Praktikum, Forschung, etc) eingeben können.

**Akzeptanzkriterien**
- Teilen einer Aktivität als Student/Mitarbeiter einer Hochschule/Universität möglich
- Eingabe einer Kategorie möglich

**Comment by dariusl93** [comment]
Im ersten Sprint wird die Klasse Activity wie im folgenden Klassendiagramm (Documentation/Sprint1/Activities.png) erweitert: https://github.com/sweIhm/sweiproject-tg2b-6/blob/master/Documentation/Sprint1/Activities.png

Beim Aufrufen der Fuktion "Add", soll man nun auch Kategorien (category) angeben können.
