### ISSUE TITLE
(UC 3) Detailansicht einer Aktivität aufrufen (Multimedia)

### ISSUE THREAD

**Issue by mariomeissner** [sweIhm/sweiproject-tg2b-6#20]
Als Student oder Mitarbeiter einer Hochschule/Universität möchte ich auf die Fotos, Videos und externe Links, die der Veranstalter der Aktivität zu Verfügung gestellt hat, Zugriff haben (bzw. visualisieren können).

**Akzeptanzkriterien**
- Öffnen der Detailansicht der Aktivitäten möglich
- Zugriff/Visualisierung der Multimedia und externer Links möglich.

**Comment by CaBeckmann** [comment]
Es ist jetzt möglich zu einer Aktivität ein Bild hochzuladen. Das Anzeigen und Bearbeiten des Bildes wurde ebenfalls implementiert.

In einem späteren Sprint kann diese Funktion noch auf das Hochladen mehrerer Bilder erweitert werden.
