### ISSUE TITLE
Visual Revamp

### ISSUE THREAD

**Issue by mariomeissner** [sweIhm/sweiproject-tg2b-6#21]
Wir sollten Änderungen zu dem Layout / Design von der Webseite einführen, um es attraktiver zu machen.

**Comment by mariomeissner** [comment]
The new blue (71265da76f5fc87caf5a7366cc4f2ac63c846baf) looks good!

**Comment by Melanie217** [comment]
I added some placeholders, and changed the colours on the Edit and Show, too. 
Anything else that should be done?

**Comment by dariusl93** [comment]
Reopened for Sprint 3
