### ISSUE TITLE
(UC 4) Aktivität teilen (Abteilung, Universität)

### ISSUE THREAD

**Issue by CaBeckmann** [sweIhm/sweiproject-tg2b-6#3]
Als Student oder Mitarbeiter einer Hochschule/Universität möchte ich beim Teilen einer Aktivität eine Abteilung (Fakultät 07, Fakultät für Informatik und Mathematik, etc) und/oder eine Universität angeben können.

**Akzeptanzkriterien**
- Teilen einer Aktivität als Student/Mitarbeiter einer Hochschule/Universität möglich
- Eingabe einer Abteilung möglich
- Eingabe einer Universität möglich

**Comment by dariusl93** [comment]
Im ersten Sprint wird die Klasse Activity wie im folgenden Klassendiagramm (Documentation/Sprint1/Activities.png) erweitert: https://github.com/sweIhm/sweiproject-tg2b-6/blob/master/Documentation/Sprint1/Activities.png

Beim Teilen einer Aktivität soll man nun auch Universität/Abteilung (University/Department ) angeben können.
