### ISSUE TITLE
(UC 4) Aktivität teilen (Tags)

### ISSUE THREAD

**Issue by CaBeckmann** [sweIhm/sweiproject-tg2b-6#4]
Als Student oder Mitarbeiter einer Hochschule/Universität möchte ich beim Teilen einer Aktivität eine beliebige Anzahl von Tags angeben können.

**Akzeptanzkriterien**
- Teilen einer Aktivität als Student/Mitarbeiter einer Hochschule/Universität möglich
- Eingabe einer beliebigen Anzahl von Tags möglich

**Comment by mariomeissner** [comment]
Ich habe das neue Atribut String[] tags mit dem entsprechenden Gettern und Settern eingebaut, damit es einfacher ist, im code mit den Tags zu arbeiten.
