### ISSUE TITLE
(UC 5) Aktivität kommentieren (Text) 

### ISSUE THREAD

**Issue by Melanie217** [sweIhm/sweiproject-tg2b-6#7]
Als Student oder Mitarbeiter einer Hochschule/Universität möchte ich eine Aktivität kommentieren können.

**Akzeptanzkriterien**

- Kommentieren einer Aktivität als Student/Mitarbeiter einer Hochschule/Universität möglich

**Comment by dariusl93** [comment]
Es ist jetzt möglich eine ausgewählte Aktivität mit Text zu kommentieren und sich diesen anzeigen zu lassen. 
In einem späteren Sprint kann diese Funktion z.B durch eine Sortierung erweitert werden.

Mangel: Beim erstmaligen aufrufen wird der Kommentar nicht in Show angezeigt, erst durch erneutes drücken des Show-Buttons ist dies gewährleistet.

**Comment by dariusl93** [comment]
Der Mangel wurde behoben.
